apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-cfg
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 256Mi
---