apiVersion: v1
kind: Secret
metadata:
  labels:
    app: grafana
  name: grafana-secrets
  namespace: monitoring
type: Opaque
data:
  GF_SECURITY_ADMIN_USER: YWRtaW4K # admin
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4K # admin
