apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # any PVC name
  name: etc-pihole
  namespace: pihole
spec:
  # access mode:
  # - ReadWriteMany (RW from multi nodes)
  # - ReadWriteOnce (RW from a node)
  # - ReadOnlyMany (R from multi nodes)
  accessModes:
    - ReadWriteOnce
  # specify microk8s-hostpath
  storageClassName: microk8s-hostpath
  resources:
    requests:
      # storage size to use
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # any PVC name
  name: etc-dnsmasq
  namespace: pihole
spec:
  # access mode:
  # - ReadWriteMany (RW from multi nodes)
  # - ReadWriteOnce (RW from a node)
  # - ReadOnlyMany (R from multi nodes)
  accessModes:
    - ReadWriteOnce
  # specify microk8s-hostpath
  storageClassName: microk8s-hostpath
  resources:
    requests:
      # storage size to use
      storage: 1Gi