apiVersion: v1
kind: Service
metadata:
  name: deluge-tcp
spec:
  type: ClusterIP
  selector:
    app: deluge
  ports:
  - name: webui
    port: 8112
    protocol: TCP
  - name: inbound-traffic-tcp
    port: 6881
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: deluge-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: deluge
  ports:
    - name: inbound-traffic-upd
      port: 6881
      protocol: UDP
---