apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-controller
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: unifi-controller
  ports:
  - name: 8080-http
    port: 8080
    protocol: TCP
  - name: 8443-https
    port: 8443
    protocol: TCP
  - name: 6789-tcp
    port: 6789
    protocol: TCP
  - name: 8843-tcp
    port: 8843
    protocol: TCP
  - name: 8880-tcp
    port: 8880
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-3478-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-controller
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: unifi-controller
  ports:
  - port: 3478
    protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-udp-1900
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-controller
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: unifi-controller
  ports:
  - port: 1900
    protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-udp-10001
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-controller
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: unifi-controller
  ports:
  - port: 10001
    protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-udp-5514
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi-controller
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: unifi-controller
  ports:
  - port: 5514
    protocol: UDP
---